config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#new'
  resources :users
  
  resources :pictures do
    collection do
      post :confirm
    end
  end
  
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    validates :content, presence: true
    mount_uploader :image, ImageUploader
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end
  
  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to pictures_path, notice: '投稿が完了しました！'
    else
      render 'new' 
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: '投稿を編集しました！' 
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: '投稿を削除しました！' 
  end
  
  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end
  
  private
  
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to pictures_path
    else
      render 'new'
    end
  end
  
  private
    
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskFb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    
    <% if logged_in? %>
      <%= link_to "ホーム", pictures_path, :class => 'nav' %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete, :class => 'nav' %>
    <% else %>
      <%= link_to "新規登録", new_user_path, :class => 'nav' %>
      <%= link_to "ログイン", new_session_path, :class => 'nav' %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
      <ul>
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="contet_box">
    <div class="field">
      <br>
      <%= form.text_area :content, :class => 'text_area' %>
    </div>
    <br>
    <div class="field">
      <%= image_tag(@picture.image.url) if @picture.image.url %>
      <br>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
    <br>
    <br>
    <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">
  　   新規投稿する
    </button>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<br>

<div class="center">
  <h1>以下の内容で、送信する。</h1>
</div>

<div class="contet_box">
  <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
    <p><%= @picture.content %></p>
    <br>
    <%= form.hidden_field :content %>
    <%= image_tag(@picture.image.url) if @picture.image? %>
    <%= form.hidden_field :image_cache %>
    <br>
    <br>
    <%= form.submit  "登録する", :class => "btn btn-lg btn-primary btn-block btn-signin" %>
  <% end %>
  <br>
  <br>
  <%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: 'back', :class => "btn btn-lg btn-primary btn-block btn-signin" %>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<br>

<div class="center">
  <h1>投稿編集</h1>
</div>

<%= render 'form', picture: @picture %>

<div class="inner">
  <%= link_to '戻る', pictures_path %>
</div>

app/views/pictures/index.html.erb
<br>

<div id="contets_box">
  <ul>
    <% @pictures.each do |picture| %>
    <div class="contet_box">
      <li>
        <dt><%= picture.user.name %>さんの投稿</dt>
        <br>
        <dd><%= picture.content %></dd>
        <br>
        <dd><%= image_tag(picture.image.url) if picture.image.url %></dd>
        <br>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action <span class="caret"></span>
          </button>
            <ul class="dropdown-menu">
              <li><%= link_to '投稿内容を編集する', edit_picture_path(picture) if picture.user_id == current_user.id %></li>
              <li><%= link_to '投稿内容を削除する', picture, method: :delete, data: { confirm: '本当に投稿を削除しますか？' } if picture.user_id == current_user.id %></li>
            </ul>
        </div>
      </li>
    </div>
    <% end %>
  </ul>
</div>

<div class="inner">
  <%= link_to '新規投稿する', new_picture_path %>
</div>

app/views/pictures/new.html.erb
<br>

<div class="center">
  <h1>新規投稿</h1>
</div>

<%= render 'form', picture: @picture %>

<div class="inner">
    <%= link_to '戻る', pictures_path %>
</div>

app/views/users/new.html.erb
<br>

<div class="center">
  <h1>新規登録</h1>
</div>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card card-container">
  <%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :名前 %>
    <%= f.text_field :name, :class => 'field' %>
    <br>
    <br>
    <%= f.label :メールアドレス %>
    <%= f.email_field :email, :class => 'field' %>
    <br>
    <br>
    <%= f.label :パスワード %>
    <%= f.password_field :password, :class => 'field' %>
    <br>
    <br>
    <%= f.label :パスワード（確認用） %>
    <%= f.password_field :password_confirmation, :class => 'field' %>
    <br>
  　<br>
  　<button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">
  　   新規登録
    </button>
  <% end %>
</div>

<div class="clear"></div>